const offers = [
  {
    id: -1,
    userId: 1,
    price: '109.90',
    quantity: 10,
    productId: -1,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -2,
    userId: 1,
    price: '149.90',
    quantity: 3,
    productId: -2,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -3,
    userId: 1,
    price: '1059.49',
    quantity: 1,
    productId: -3,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -4,
    userId: 1,
    price: '1459.49',
    quantity: 20,
    productId: -4,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -5,
    userId: 1,
    price: '859.49',
    quantity: 10,
    productId: -5,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -6,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -6,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -7,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -7,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -8,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -8,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -9,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -9,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -10,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -10,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -11,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -11,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -12,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -12,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -13,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -13,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -14,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -14,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -15,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -15,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -16,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -16,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -17,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -17,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -18,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -18,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -19,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -19,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -20,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -20,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -21,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -21,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -22,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -22,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -23,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -23,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -24,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -24,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -25,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -25,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -26,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -26,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -27,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -27,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -28,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -28,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -29,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -29,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -30,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -30,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -31,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -31,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -32,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -32,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -33,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -33,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -34,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -34,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -35,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -35,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -36,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -36,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -37,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -37,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -38,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -38,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -39,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -39,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -40,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -40,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -41,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -41,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -42,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -42,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -43,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -43,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -44,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -44,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -45,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -45,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -46,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -46,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -47,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -47,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -48,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -48,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -49,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -49,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -50,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -50,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -51,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -51,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -52,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -52,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -53,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -53,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -54,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -54,
    status: 'ACTIVE',
    version: 1,
  },
  {
    id: -55,
    userId: 1,
    price: '149.49',
    quantity: 1,
    productId: -55,
    status: 'ACTIVE',
    version: 1,
  },
];

module.exports = {
  offers: offers,
};
