version: '3.8'
services:
  db:
    container_name: db_container
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecommerce_db
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgres/data
    networks:
      network:
        ipv4_address: 10.5.0.10

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      network:
        ipv4_address: 10.5.0.11

  keycloak:
    ports:
      - '28080:8080'
    environment:
      - KEYCLOAK_ADMIN=keycloak_admin
      - KEYCLOAK_ADMIN_PASSWORD=keycloak_admin
    image: keycloak/keycloak:22.0.1
    volumes:
      - ./config/keycloak:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
    networks:
      network:
        ipv4_address: 10.5.0.12

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      network:
        ipv4_address: 10.5.0.13

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      network:
        ipv4_address: 10.5.0.14

volumes:
  db:
    driver: local

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1