package com.ecommerce.shared.api.dto;

public interface ErrorCode {

    String FIELD_REQUIRED = "FIELD_REQUIRED";
    String SERVER_ERROR = "SERVER_ERROR";
    String CONCURRENT_MODIFICATION_ERROR = "CONCURRENT_MODIFICATION_ERROR";
    String OFFER_NOT_FOUND = "OFFER_NOT_FOUND";
    String CART_NOT_FOUND = "CART_NOT_FOUND";
    String INACTIVE_OFFER_FOR_ORDER = "INACTIVE_OFFER_FOR_ORDER";
    String OFFER_RUN_OUT_OF_STOCK = "OFFER_RUN_OUT_OF_STOCK";
    String PASSWORD_DOES_NOT_MATCH = "PASSWORD_DOES_NOT_MATCH";
    String FORBIDDEN_ACCESS = "FORBIDDEN_ACCESS";
    String UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS";
    String IAM_ERROR = "IAM_ERROR";
    String IAM_USER_ALREADY_EXISTS = "IAM_USER_ALREADY_EXISTS";
    String OFFER_WITH_PRODUCT_EXITS = "OFFER_WITH_PRODUCT_EXITS";
    String ORDER_WITH_PRODUCT_EXITS = "ORDER_WITH_PRODUCT_EXITS";
    String ORDER_WITH_OFFER_EXITS = "ORDER_WITH_OFFER_EXITS";
    String INACTIVE_ACCOUNT = "INACTIVE_ACCOUNT";
}
