// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'field': string;
  'fieldArea': string;
  'imgBox': string;
  'loadedImage': string;
  'quantity': string;
}
export const cssExports: CssExports;
export default cssExports;
