INSERT INTO USERS (ID, EMAIL, FIRST_NAME, LAST_NAME, TAX_ID, STATUS) VALUES (-1000, 'johnny.lee@mail.com', 'Johnny', 'Lee', '19027148', 'ACTIVE');
do $$
DECLARE
   JOHNNY_ID INTEGER;
BEGIN
   SELECT ID
   INTO JOHNNY_ID
   FROM USERS WHERE EMAIL = 'johnny.lee@mail.com';

   INSERT INTO ADDRESSES (ID, USER_ID, COUNTRY, CITY, STREET, BUILDING_NO, FLAT_NO, POSTAL_CODE)
   VALUES (-1000, JOHNNY_ID, 'England', 'London', 'Euston Rd.', '71', '3c', 'GVHC+XW');
END
$$;