CREATE TABLE PRODUCTS (
    ID SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    EAN VARCHAR(20) NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    IMAGE_NAME VARCHAR(100),
    DESCRIPTION VARCHAR(500),
    VERSION INTEGER NOT NULL DEFAULT 0
);