CREATE TABLE OFFERS (
    ID SERIAL NOT NULL PRIMARY KEY,
    USER_ID INTEGER NOT NULL REFERENCES USERS,
    PRODUCT_ID INTEGER NOT NULL REFERENCES PRODUCTS,
    QUANTITY INTEGER NOT NULL,
    PRICE DECIMAL NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    VERSION INTEGER NOT NULL DEFAULT 0
);