CREATE TABLE CART_ITEMS (
    ID SERIAL NOT NULL PRIMARY KEY,
    CART_ID INTEGER NOT NULL REFERENCES CARTS,
    OFFER_ID INTEGER NOT NULL REFERENCES OFFERS,
    QUANTITY INTEGER NOT NULL,
    VERSION INTEGER NOT NULL DEFAULT 0
);