CREATE TABLE ORDERS (
    ID SERIAL NOT NULL PRIMARY KEY,
    BUYER_ID INTEGER NOT NULL REFERENCES USERS,
    DELIVERY_METHOD VARCHAR(20) NOT NULL,
    DELIVERY_STATUS VARCHAR(20) NOT NULL,
    PAYMENT_METHOD VARCHAR(20) NOT NULL,
    PAYMENT_STATUS VARCHAR(20) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    VERSION INTEGER NOT NULL DEFAULT 0
);