CREATE TABLE ORDER_LINES (
    ID SERIAL NOT NULL PRIMARY KEY,
    ORDER_ID INTEGER NOT NULL REFERENCES ORDERS,
    OFFER_ID INTEGER NOT NULL REFERENCES OFFERS,
    QUANTITY INTEGER NOT NULL,
    VERSION INTEGER NOT NULL DEFAULT 0
);